language: bash

services:
  - docker

before_script:
  - docker -v
  - docker build -t $APP_IMAGE .
  - docker run
    -e ABS_STORAGE_API_URL
    -e ABS_STORAGE_API_TOKEN
    -e SNOWFLAKE_STORAGE_API_URL
    -e SNOWFLAKE_STORAGE_API_TOKEN
    -e SYNAPSE_STORAGE_API_URL
    -e SYNAPSE_STORAGE_API_TOKEN
    $APP_IMAGE
    composer ci

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
