version: '2'
services:
  dev:
    build: .
    environment:
      - ABS_STORAGE_API_URL
      - ABS_STORAGE_API_TOKEN
      - SNOWFLAKE_STORAGE_API_URL
      - SNOWFLAKE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL
      - SYNAPSE_STORAGE_API_TOKEN
    volumes:
      - ./:/code
      - ./data:/data
